language: cpp
compiler: gcc


notifications:
  email: false

services:
  - docker

addons:
  apt:
    packages:
      - realpath wget git realpath
matrix:
  include:
    - env: INSTALL_PREFIX=/usr PROJECT_BUILD_DIR=/tmp/build QT_SELECT=qt5
      addons:
        apt:
          packages:
            - realpath
            - wget
            - git
            - cmake
            - desktop-file-utils
            - libglib2.0-dev
            - python-pip

      install:
        - sudo pip install conan --upgrade
        - sudo pip install conan_package_tools
        - conan user
        - conan remote add appimage-community https://api.bintray.com/conan/appimage-conan-community/public-conan --insert=0
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        - conan remote add azubieta https://api.bintray.com/conan/azubieta/AppImage

      script:
        - mkdir build && cd build
        - conan install .. --build missing -s cppstd=11 -s compiler.libcxx=libstdc++11
        - cmake -DUSE_CONAN=ON .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
        - make install -j`nproc` DESTDIR=AppDir
        - . activate_run.sh
        - INSTALL_PREFIX=" " ../.travis/build_appimage.sh

    ## Build Debian buster package
    - env: PKG_BUILD=DEBIAN_BUSTER
      script:
        - .travis/debian_buster/build_package.sh

    ## Build Centos 7 package
    - env: PKG_BUILD=CENTOS_7
      script:
        - .travis/centos_7/build_package.sh

    ## Build Ubuntu Bionic package
    - env: PKG_BUILD=UBUNTU_BIONIC
      script:
        - .travis/ubuntu_bionic/build_package.sh

    ## Build OpenSuse Leap package
    - env: PKG_BUILD=OPENSUSE_LEAP
      script:
        - .travis/opensuse_leap/build_package.sh

    ## Build ARCH package
    - env: PKG_BUILD=ARCH
      dist: xenial
      script:
        - .travis/arch/build_package.sh

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh appimage-cli-tool*.AppImage*
  - bash upload.sh docker-build-release/appimage-cli-tool*.rpm
  - bash upload.sh docker-build-release/appimage-cli-tool*.deb
  - bash upload.sh docker-build-release/appimage-cli-tool*.pkg.tar.xz
